Unity-Technologies/2d-extras

- Assets/Tilemap/Brushes/Line Brush/Scripts/Editor/LineBrush.cs
Added fillGaps to LineBrush to allow for continuous lines with no empty gaps.
> Added fillGaps option to LineBrush

- Assets/Tilemap/Tiles/Animated Tile/Scripts/AnimatedTile.cs
Fixed errors that happened within editor when creating a new animated tile
Fixed default save name of animated tile
> Animated Tile Update

- Assets/Tilemap/Tiles/Animated Tile/Scripts/AnimatedTile.cs
The ColliderType For AnimationTiles is not Generated , Added the necessary code to choose the collider type in the inspector settings.
> Added Necessary Collider Editor Fields for AnimationTiles

- Assets/Tilemap/Brushes/Coordinate Brush/Scripts/Editor/CoordinateBrush.cs
- Assets/Tilemap/Tiles/Weighted Random Tile/WeightedRandomTile.cs
This makes it easier to see the size of your box fill at least.
> CoordinateBrush: Added size to displayed handle

- Assets/Tilemap/Tiles/Rule Override Tile.meta
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts.meta
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor.meta
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs.meta
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs.meta
- Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs
I proposed this feature on https://github.com/Unity-Technologies/2d-extras/issues/4 a few months ago, but because the main branch has not progressed, I hope to push this forward, so I implemented this function.
I don't know what the official expectation is, but if this doesn't suit your expectations, just reject the pull request.
> Add RuleOverrideTile

- Assets/Tilemap/Brushes/Coordinate Brush/Scripts/Editor/CoordinateBrush.cs
- Assets/Tilemap/Brushes/Line Brush/Scripts/Editor/LineBrush.cs
- Assets/Tilemap/Brushes/Prefab Brush/Scripts/Editor/PrefabBrush.cs
- Assets/Tilemap/Brushes/Random Brush/Scripts/Editor/RandomBrush.cs
- Assets/Tilemap/Tiles/Animated Tile/Scripts/AnimatedTile.cs
- Assets/Tilemap/Tiles/Pipeline Tile/Scripts/PipelineTile.cs
- Assets/Tilemap/Tiles/Random Tile/Scripts/RandomTile.cs
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs
- Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs
- Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs
- Assets/Tilemap/Tiles/Terrain Tile/Scripts/TerrainTile.cs
- Assets/Tilemap/Tiles/Weighted Random Tile/WeightedRandomTile.cs
It was getting a bit messy having all the tiles and brushes directly under the Create menu, so I grouped them in separate submenus.
> Reorganized Assets/Create menu to group the tiles and brushes. 

- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs
- Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs
- Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs
If true, RuleTile and RuleOverrideTile will not connect.
If false, it will connect.
> Add m_OverrideSelf to RuleOverrideTile

- Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/CustomRuleTileMenu.cs
See: https://github.com/Unity-Technologies/2d-extras/issues/89
> Use the API of Unity 2019

- Editor/Tiles/IsometricRuleTile/IsometricRuleTileEditor.cs
The problem occurred in https://github.com/Unity-Technologies/2d-extras/pull/140/commits/f34aafb8c14b8fd77d53e75c283b36f4499a1208#diff-b6e539c6a9c1780689ab16c2780a393bR69-R70.
> Fixed #153

- Editor/Tiles/HexagonalRuleTile/HexagonalRuleTileEditor.cs
- Editor/Tiles/IsometricRuleTile/IsometricRuleTileEditor.cs
- Editor/Tiles/RuleOverrideTile/RuleOverrideTileEditor.cs
- Editor/Tiles/RuleTile/RuleTileEditor.cs
- [RuleTile / IsometricRuleTile / RuleOverrideTile] Support tiling rules preview
- [RuleOverrideTile] Add static preview
- [CustomRuleTile] Support custom field of Object type
- Tiling rules preview not support of HexagonalRuleTile now. (No idea how to show for the time being)
> Support tiling rules preview

- Editor/Brushes/PrefabBrushes/BasePrefabBrush.cs
- Editor/Brushes/PrefabBrushes/PrefabBrush/PrefabBrush.cs
Allows rotation for prefabs placed via PrefabBrush
> Add rotation to PrefabBrush

- Editor/Brushes/PrefabBrushes/PrefabBrush/PrefabBrush.cs
Adds a method to the prefab brush so that the brush supports the box fill operation.
> Add box fill to prefab brush

- Editor/Brushes/PrefabBrushes/PrefabBrush/PrefabBrush.cs
#232 
https://streamable.com/rvbjy6
> Box erase fix

- Editor/Menu/MenuItemOrder.cs
- Editor/Tiles/RuleOverrideTile/AdvancedRuleOverrideTileEditor.cs
- Editor/Tiles/RuleTile/RuleTileEditor.cs
-Validate Ids for TilingRules for the AdvancedRuleOverrideTileEditor
-Fix null exception error for RuleTileEditor
-Fix menu order for RuleOverrideTile
> Advancedruleoverride

- Editor/Brushes/PrefabBrushes/PrefabBrush/PrefabBrush.cs
Took a comment for a boolean field and put it as a tooltip that can be viewed in the editor.
> Added a tooltip for the prefab brush "Erase Any Objects" field

- Documentation~/RuleTile.md
- Editor/Tiles/RuleTile/RuleTileEditor.cs
- Runtime/Tiles/RuleTile/RuleTile.cs
Add randomized anim speed to `RuleTile`
> -Randomized animation speed for RuleTile (#258)

- Editor/Tiles/RuleTile/RuleTileEditor.cs
- Runtime/Tiles/RuleTile/RuleTile.cs
"+" button allows Add and Duplicate when a Rule is selected, which will add a new Rule below the currently selected Rule or duplicate the currently selected Rule and add it below it.
> Ruletileeditorinsert

- Editor/Tiles/RuleTile/RuleTileEditor.cs
- Add field to change number of TilingRules
- Add drag and drop field accepting Sprites to fill out the initial TilingRule list
- Add blank space at the end of TilingRules list
> Rule Tile Editor UI

- Editor/Brushes/TintBrushSmooth/TintBrushSmooth.cs
- Editor/Brushes/TintBrushSmooth/TintTextureGeneratorEditor.cs
- Editor/Brushes/TintBrushSmooth/TintTextureGeneratorEditor.cs.meta
- Runtime/Brushes/TintTextureGenerator.cs
https://github.com/Unity-Technologies/2d-extras/issues/286
> Convert cell positions to world positions using the Grid in Tint Brush Smooth

- package.json
Update test package version from 2.2.0 to 3.0.0 to match package version
> Update Test Package version

- Runtime/Tiles/RuleOverrideTile/RuleOverrideTile.cs
https://forum.unity.com/threads/custom-property-overrides-in-ruleoverridetiles-based-on-customized-ruletiles.1237204/
> -Clone Tile into temporary tile when preparing overrides

- Runtime/GridInformation/GridInformation.cs
> -Implement IEquatable for GridInformationKey
