Assets/Tilemap/Tiles/Random Tile/Scripts/RandomTile.cs, Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs
The editor was clearing my sprites when changing the array size from 9 to 10 so i changed the field type to DelayedIntField.
Thanks,
Ethan
=> Changed from IntField to DelayedIntField

Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs
Currently if you want to set state to X, you need to click twice with left mouse button. I propose toggling in reverse direction. With this change you can click once with right mouse button to set state to X and click second time to set it to ✓. Toggling in normal direction with left mouse button will still work, of course.
=> Allow toggling of state in reverse direction

Assets/Tilemap/Tiles/Weighted Random Tile/WeightedRandomTile.cs
The weighted tile algorithm was showing a bias towards the first sprite. For example if there's 3 sprites with a weight of (1, 1,1) then the output from the random numbers (0, 1, 2) would be sprites (0, 0, 1).
If the weights were (2, 2, 2) the outputs from random numbers (0, 1, 2, 3, 4, 5) would be sprites (0, 0, 0, 1, 1, 2).
Weights (3, 3, 3) with random numbers (0, 1, 2, 3, 4, 5, 6, 7, 8) would produce (0, 0, 0, 0, 1, 1, 1, 2, 2).
This PR fixes the issue.
=> Fixed weighted tile algorithm

Assets/Tilemap/Tiles/Rule Override Tile.meta, Assets/Tilemap/Tiles/Rule Override Tile/Scripts.meta, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor.meta, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs.meta, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs.meta, Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs, Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs
Because the last pull request merge conflict and re-pull.
This solution can customize RuleTile without writing Editor code.
If you have any ideas welcome to join the discussion.
Issue: https://github.com/Unity-Technologies/2d-extras/issues/27
- Inheritable RuleTile
- Customizable attributes
- Can expand or rewrite neighbor rules and GUI display
- Can be used by RuleOverrideTile
- Template script (Menu: Assets/Create/Custom Rule Tile Script)
- Neighbor rules tooltip
- Backward compatible
- Custom Attributes:
```csharp
public class MyTile : RuleTile {
public string tileId;
public bool isWater;
}
```
- Custom Rules:
```csharp
public class MyTile : RuleTile<MyTile.Neighbor> {
public class Neighbor {
public const int MyRule1 = 0;
public const int MyRule2 = 1;
}
public override bool …
```
=> Customizable RuleTile #2

Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs, Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs
Rule tiles are great. But not allowing you to specify a game object per rule is something that limits its power.
Hope this can help anyone trying to pull advanced stuff in combination with rule tiles. I know I needed this, and I hope this can help others too.
=> Added an option to choose Game Objects per rule in rule tiles

Assets/Tilemap/Brushes/Prefab Brush/Scripts/Editor/PrefabBrush.cs
PrefabBrush is broken in Unity 2018.3: after selecting the target tilemap, you can only draw one prefab onto it. Subsequent drawing gives a 'NullReferenceException' error. 
This problem has been reported at Unity Answers too:
https://answers.unity.com/questions/1571608/prefab-brush-from-2d-extras-not-working-in-tilemap.html
=> A simple fix for PrefabBrush to address the 'NullReferenceException' issue in 2018.3

Assets/Tilemap/Brushes/Prefab Brush/Scripts/Editor/PrefabBrush.cs
Updated PrefabBrush.cs Paint method for runtime, solving the issue that if a prefab is painted before runtime it can have another painted ontop of it at runtime.
=> Updated PrefabBrush.cs Paint method for runtime 

Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/PopulateRuleOverrideTileWizard.cs, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/PopulateRuleOverrideTileWizard.cs.meta, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs
I've created a bare-bones wizard that makes it easy to create override tiles based on identical tile-sheets. I made it because I needed an easy way to create rule override tile sets based on a template. Otherwise, I would need to set 30+ overrides, one by one, whenever I created a new tile set.
It does have a few glaring limitations/issues that should probably be resolved before merging this into the main build. Sadly, I probably won't be the one making these fixes; it fulfills my needs as-is. However, I'm creating the PR in hopes that someone else might find this useful.
- It cares about the naming schemes of individual sprites. (It searches for the underscore followed by a number. For example, Template<em><b>_23</b></em> is matched against River<em><b>_23</b></em>. Whatever comes before …
=> Pre-populate rule override tile based on sprite sheet

Assets/Tilemap/Tiles/Rule Override Tile/Scripts/Editor/RuleOverrideTileEditor.cs, Assets/Tilemap/Tiles/Rule Override Tile/Scripts/RuleOverrideTile.cs, Assets/Tilemap/Tiles/Rule Tile/Scripts/Editor/RuleTileEditor.cs, Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs
Fix issue: https://github.com/Unity-Technologies/2d-extras/issues/100
In the past, RuleOverrideTile was refreshed when calling StartUp(), but since GetTileData() will be called earlier than StartUp(), there is no guarantee that the data will be correct in the StartUp() refresh.
The RuleOverrideTile will now be refreshed the first time data is requested. And update at the same time when the source tile is updated.
=> Fix RuleOverrideTile update timing

Assets/Tilemap/Brushes/Coordinate Brush/Scripts/Editor/CoordinateBrush.cs
Fix for #112 
Minimally removed the z integer in the CoordinateBrush class. The coordinate brush now correctly uses the Tile Palette's Z Position field like other brushes.
=> Coordinate Brush correctly using Tile Palette's Z Position field.

Editor/Brushes/PrefabBrush/PrefabBrush.cs
Made the change to make sure that you can't accidentally place several prefabs at the same tile.
#124
=> Made the prefab brush erase the previous tile before placing a new one

Editor/Tiles/HexagonalRuleTile/HexagonalRuleTileEditor.cs, Editor/Tiles/IsometricRuleTile/IsometricRuleTileEditor.cs, Editor/Tiles/RuleOverrideTile/RuleOverrideTileEditor.cs, Editor/Tiles/RuleTile/RuleTileEditor.cs, Runtime/Tiles/HexagonalRuleTile/HexagonalRuleTile.cs, Runtime/Tiles/RuleOverrideTile/RuleOverrideTile.cs, Runtime/Tiles/RuleTile/RuleTile.cs
- Backward compatible with RuleTile and IsometricRuleTile.
- Not backward compatible with HexagonalRuleTile. The rules need to be reset after the update.
- [RuleTile] changed from using index to using position.
- [RuleTile] Additional storage rule position.
- [RuleTile] Delete ```DontCare``` rule.
- [RuleTile] Rule list increased ```Extend Neighbor``` toggle. When selected, it will increase the rule range that can be set.
- [RuleTile] No longer fixed to checking around 8 rules.
- [RuleTile] ```RefreshTile()``` will refresh affected remote Tiles.
- [RuleTile] Delete ```GetMatchingNeighboringTiles()```, no longer get nearby Tiles in advance, the performance is affected. (may be changed to cache later)
- [IsometricRuleTile] Rewrite.
- [HexagonalRuleTile] Rewrite.
Transfrom rule icon is no …
=> Support unlimited rule size

Editor/Brushes/LineBrush/LineBrush.cs
Made the Paint method function like the one for the default brush while stuff is being moved.
#121
=> Fix for "[LineBrush] Tiles disappear after selection and drag"

Editor/Tiles/HexagonalRuleTile/HexagonalRuleTileEditor.cs, Editor/Tiles/IsometricRuleTile/IsometricRuleTileEditor.cs, Editor/Tiles/RuleTile/RuleTileEditor.cs, Runtime/Tiles/HexagonalRuleTile/HexagonalRuleTile.cs, Runtime/Tiles/RuleTile/RuleTile.cs
Fixed some cases where the tile refresh did not refresh the affected remote tile.
https://github.com/Unity-Technologies/2d-extras/pull/148/commits/8de8e1bc648a5eb4d4ea52aee13efb4ea57dc6b1 Update:
```RefreshNearTiles()``` and ```RefreshRemoteTiles()``` are used to speed up ```RefreshTile()```. Most people don't use the 5x5 rule size. The algorithm assumes the size of the past 3x3 rule. More than 3x3 will do extra calculations to ensure that users will not be affected by the upgrade.
Now change to Caching all RuleTile neighbor positions for the Tilemap, speedup 5x5 to same as 3x3.
=> Fix remote positions missing of MirrorXY

Runtime/Tiles/RuleTile/RuleTile.cs
Performed fixes to the math in `RuleTile`'s `StartUp()` method so that instantiated `GameObject`s match the rotation and scale transformations of sprites (done internally by Unity's `SpriteRenderer`).  The desired intent here is that if you create a `RuleTile` with 3D `GameObject`s and 2D `Sprite`s that are visually a flattened version of the 3D art _(imagine 3D walls in a maze, and 2D sprites showing the top-down outlines of the walls)_, they should **always** match up with each other in the Unity Editor and Player.
* Added application of the `Tilemap`'s `orientationMatrix` to the `transform` matrix.  This is necessary for `instantiatedGameObject` to be rotated correctly when using any of the `Tilemap` `orientation` & `Grid` `cellSwizzle` modes beyond the default `.XY` & `.XYZ`.
* Now …
=> Fixed RuleTile instantiatedGameObject rotation/scale

Editor/Tiles/RuleOverrideTile/AdvancedRuleOverrideTileEditor.cs, Editor/Tiles/RuleOverrideTile/RuleOverrideTileEditor.cs, Editor/Tiles/RuleTile/RuleTileEditor.cs, Runtime/Tiles/HexagonalRuleTile/HexagonalRuleTile.cs, Runtime/Tiles/RuleOverrideTile/AdvancedRuleOverrideTile.cs, Runtime/Tiles/RuleOverrideTile/RuleOverrideTile.cs, Runtime/Tiles/RuleTile/RuleTile.cs
- Support [HideInInspector] to custom fields
- Add [DontOverride] attribute for custom fields
- Make RuleTile Api public
Sometime custom field is use to control the tiling rules(like HexagonalRuleTile.m_FlatTop), it should not editable in RuleOverrideTile. Use [DontOverride] can make the field hidden in RuleOverrideTile.
=> [CustomRuleTile] Support HideInInspector, DontOverride attributes

Runtime/Tiles/WeightedRandomTile/WeightedRandomTile.cs
Related to issue: 
https://github.com/Unity-Technologies/2d-extras/issues/178
WeightedRandomTile uses
`Random.InitState((int) hash);`
to set a seed but fails to return it to its original state when its finished. This breaks projects for people who are doing procedural generation. (It resets the seed I already set!)
I noticed that RandomTile doesn't have this issue. So I poked around inside, and saw that it saves the current `Random.state`, and then sets the state back up when its finished doing its thing.
=> Fixed WeightedRandomTile messing up Random.seed!

Editor/Brushes/PrefabBrushes/PrefabBrush/PrefabBrush.cs, Editor/Brushes/PrefabBrushes/PrefabRandomBrush/PrefabRandomBrush.cs, Editor/Brushes/RandomBrush/RandomBrush.cs, Runtime/Tiles/AnimatedTile/AnimatedTile.cs, Runtime/Tiles/HexagonalRuleTile/HexagonalRuleTile.cs, Runtime/Tiles/IsometricRuleTile/IsometricRuleTile.cs, Runtime/Tiles/PipelineTile/PipelineTile.cs, Runtime/Tiles/RandomTile/RandomTile.cs, Runtime/Tiles/RuleOverrideTile/AdvancedRuleOverrideTile.cs, Runtime/Tiles/RuleOverrideTile/RuleOverrideTile.cs, Runtime/Tiles/RuleTile/RuleTile.cs, Runtime/Tiles/TerrainTile/TerrainTile.cs, Runtime/Tiles/WeightedRandomTile/WeightedRandomTile.cs
Add option to create **Tiles** and **Brushes** assets grouped by **2D Extras** menu, after **Tile**.
The order number was chosen based on [this guide](https://blog.redbluegames.com/guide-to-extending-unity-editors-menus-b2de47a746db).
=> Option to Create Tiles and Brushes grouped on 2D Extras

Editor/Brushes/GameObjectBrush/GameObjectBrush.cs, Editor/Brushes/PrefabBrushes/BasePrefabBrush.cs
Take into account the Anchor when using GetObjectsInCell as Anchor can span over a cell.
=> -Account for Anchor when using GetObjectsInCell in PrefabBrush and GameObjectBrush

Editor/Tiles/HexagonalRuleTile/HexagonalRuleTileEditor.cs
Issue: https://github.com/Unity-Technologies/2d-extras/issues/253
HexagonalRuleTile matrix GUI incorrect, it only occur with m_FlatTop enabled.
=> Fix flat top HexagonalRuleTile rules GUI

Runtime/Tiles/RuleTile/RuleTile.cs
-Check if there are any invalid Tilemaps before releasing cached data
-When refreshing Tile, check if the neighboring Tile is the same RuleTile before checking if it has the offset (if the RuleTiles are exactly the same, they will have the same offsets).
-Less lookups to validate if the Tilemap has changed in used Tiles
=> RuleTile optimisations

Editor/Brushes/PrefabBrushes/PrefabRandomBrush/PrefabRandomBrush.cs
If brushTarget is allowed to be null we should first check for null and then check value of layer property.
=> Fix possible NullReferenceException in PrefabRandomBrush

Editor/Brushes/PrefabBrushes/BasePrefabBrush.cs
There was an annoying Unity crash when I was undoing some operations on tilemaps. Finally found the repro steps and found the cause of the crash. We need to register Undo.SetTransformParent when modifying the parent of an instantiated object.
=> Fix Unity crash when performing undo operation on the prefab brush.
